dependencies:
  - python=3
  - pip:
    - ipykernel
    - snownlp
    - ggplot
    - plotnine
    - xlrd
    - pandas
    - spacy
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
